# hosts.ini
# Inventaire Ansible — liste toutes les machines

# ── VMs par rôle ─────────────────────────────────────────
[webservers]
vm-web-01 ansible_host=172.19.14.66

[databases]
vm-db-01 ansible_host=172.19.14.63

[monitoring]
vm-zabbix-01 ansible_host=172.19.14.xx

[backup]
vm-veeam-01 ansible_host=172.19.14.xx

# ── Groupe global VMs ────────────────────────────────────
[vms:children]
webservers
databases
monitoring
backup

[vms:vars]
ansible_user                 = sysadmin
ansible_ssh_private_key_file = ~/.ssh/id_rsa
ansible_python_interpreter   = /usr/bin/python3
ansible_ssh_common_args      = '-o StrictHostKeyChecking=no'

# ── LXC ──────────────────────────────────────────────────
[dns]
lxc-dns-1  ansible_host=172.19.14.200
lxc-dns-2  ansible_host=172.19.14.201

[db]
lxc-db  ansible_host=172.19.14.202

[app]
lxc-app  ansible_host=172.19.14.203

# ── Groupe global LXC ────────────────────────────────────
[lxc_containers:children]
dns
db
app

[lxc_containers:vars]
ansible_user                 = root
ansible_password             = admin@2026
ansible_ssh_private_key_file = ~/.ssh/id_rsa
ansible_python_interpreter   = /usr/bin/python3
ansible_ssh_common_args      = '-o StrictHostKeyChecking=no'

# ── Groupe global tout ───────────────────────────────────
[all_machines:children]
vms
lxc_containers