# hosts.ini
# Inventaire Ansible — liste toutes les machines

# ── VMs par rôle ─────────────────────────────────────────
[webservers]
vm-web-01 ansible_host=172.19.14.57

[databases]
vm-db-01 ansible_host=172.19.14.55

[monitoring]
vm-zabbix-01 ansible_host=172.19.14.52 ansible_user=sysadmin

[backup]
vm-veeam-01 ansible_host=172.19.14.58

[AD]
vm-ad-01            ansible_host=172.19.14.82

[WDS]
vm-wds-01       ansible_host=172.19.14.66

# ── Groupe global VMs ────────────────────────────────────
[vms:children]
webservers
databases
monitoring
backup


[vms:vars]
ansible_user                 = sysadmin
ansible_ssh_private_key_file = ~/.ssh/id_rsa
ansible_become_method        = sudo 
ansible_python_interpreter   = /usr/bin/python3
ansible_ssh_common_args      = '-o StrictHostKeyChecking=no'

[windows_vms:children]
AD
WDS

[windows_vms:vars]
ansible_user=Administrateur
ansible_password=TonMotDePasse
ansible_connection=winrm
ansible_port=5985
ansible_winrm_server_cert_validation=ignore

# ── LXC ──────────────────────────────────────────────────
[dns]
lxc-dns-1  ansible_host=172.19.14.51
lxc-dns-2  ansible_host=172.19.14.46

[db]
lxc-db  ansible_host=172.19.14.80

[app]
lxc-app  ansible_host=172.19.14.81

[nfs]
lxc-nfs ansible_host=172.19.14.79

# ── Groupe global LXC ────────────────────────────────────
[lxc_containers:children]
dns
db
app
nfs


[lxc_containers:vars]
ansible_user                 = root
ansible_password             = admin@2026
ansible_ssh_private_key_file = ~/.ssh/id_rsa
ansible_python_interpreter   = /usr/bin/python3
ansible_ssh_common_args      = '-o StrictHostKeyChecking=no'

# ── Groupe global tout ───────────────────────────────────
[all_machines:children]
vms
lxc_containers