---
- name: "Installation et Configuration Automatisée de Zabbix 7.0 LTS"
  hosts: monitoring
  become: yes
  vars:
    zabbix_db_password: "azerty123"
    zabbix_version: "7.0"
    ubuntu_version: "24.04"

  tasks:
    - name: "0. Suppression définitive des sources CD-ROM"
      shell: |
        find /etc/apt/ -name "*.sources" -exec sed -i '/cdrom/d' {} +
        find /etc/apt/ -name "*.list" -exec sed -i '/cdrom/d' {} +
      args:
        warn: false

    - name: 1. Installer les dépendances Python pour PostgreSQL
      apt:
        name: 
          - python3-psycopg2
          - acl # Nécessaire pour que 'become_user: postgres' fonctionne
        state: present
        update_cache: yes

    - name: 2. Ajouter le dépôt officiel Zabbix
      apt:
        deb: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_{{ zabbix_version }}+ubuntu{{ ubuntu_version }}_all.deb"

    - name: 3. Installer la pile Zabbix (Serveur, Frontend, Agent, DB)
      apt:
        name:
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - php8.3-pgsql
          - zabbix-nginx-conf
          - zabbix-sql-scripts
          - zabbix-agent
          - postgresql
        state: present
        update_cache: yes

    - name: 4. Configurer la base de données PostgreSQL
      become_user: postgres
      block:
        - postgresql_user:
            name: zabbix
            password: "{{ zabbix_db_password }}"
        - postgresql_db:
            name: zabbix
            owner: zabbix

    - name: 5. Importer le schéma SQL initial (Patienter ~1-2 min)
      shell: "zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | PGPASSWORD='{{ zabbix_db_password }}' psql -h localhost -U zabbix zabbix"
      args:
        creates: /var/lib/postgresql/.zabbix_imported 

    - name: 6. Marquer l'import comme terminé
      file:
        path: /var/lib/postgresql/.zabbix_imported
        state: touch

    - name: 7. Configurer le mot de passe dans zabbix_server.conf
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^# DBPassword='
        line: "DBPassword={{ zabbix_db_password }}"

    - name: 8. Configurer Nginx pour Zabbix
      replace:
        path: /etc/zabbix/nginx.conf
        regexp: '# listen 80;'
        replace: 'listen 80;'

    - name: 9. Définir le nom du serveur dans Nginx
      replace:
        path: /etc/zabbix/nginx.conf
        regexp: '# server_name example.com;'
        replace: "server_name {{ ansible_host }};"

    - name: 10. Démarrer et Activer tous les services
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - postgresql
        - zabbix-server
        - zabbix-agent
        - nginx
        - php8.3-fpm